fixed and removed the docker action for now

diff --git a/.github/workflows/sql_database.yml b/.github/workflows/sql_database.yml
--- a/.github/workflows/sql_database.yml
+++ b/.github/workflows/sql_database.yml
@@ -37,28 +37,28 @@ jobs:
         # Push image to ECR
         docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
 
-    - name: Setup SSH Key
-      run: |
-        mkdir -p ~/.ssh
-        echo "${{ secrets.EC2_SSH_PRIVATE_KEY }}" > ~/.ssh/assignment1.pem
-        chmod 600 ~/.ssh/assignment1.pem
+    # - name: Setup SSH Key
+    #   run: |
+    #     mkdir -p ~/.ssh
+    #     echo "${{ secrets.EC2_SSH_PRIVATE_KEY }}" > ~/.ssh/assignment1.pem
+    #     chmod 600 ~/.ssh/assignment1.pem
   
-    - name: Deploy to EC2 and Run Containers
-      run: |
-        ssh -t -o StrictHostKeyChecking=no -i ~/.ssh/assignment1.pem ec2-user@${{ secrets.EC2_PUBLIC_IP }} << 'EOF'
+    # - name: Deploy to EC2 and Run Containers
+    #   run: |
+    #     ssh -t -o StrictHostKeyChecking=no -i ~/.ssh/assignment1.pem ec2-user@${{ secrets.EC2_PUBLIC_IP }} << 'EOF'
 
-        # Ensure Docker is installed
-        if ! command -v docker &> /dev/null
-        then
-            echo "Docker not found! Installing..."
-            sudo yum update -y
-            sudo yum install -y docker
-            sudo systemctl start docker
-            sudo systemctl enable docker
-            sudo usermod -aG docker ec2-user
-        fi
-        
-        docker network create webapp-network || true
-        docker pull ${{ steps.login-ecr.outputs.registry }}/clo835-assignment1-sql-image:v0.1     
-        docker run -d --name mysql -p 8080:80 ${{ steps.login-ecr.outputs.registry }}/clo835-assignment1-sql-image:v0.1        
-        EOF
+    #     # Ensure Docker is installed
+    #     if ! command -v docker &> /dev/null
+    #     then
+    #         echo "Docker not found! Installing..."
+    #         sudo yum update -y
+    #         sudo yum install -y docker
+    #         sudo systemctl start docker
+    #         sudo systemctl enable docker
+    #         sudo usermod -aG docker ec2-user
+    #     fi
+
+    #     docker network create webapp-network || true
+    #     docker pull ${{ steps.login-ecr.outputs.registry }}/clo835-assignment1-sql-image:v0.1     
+    #     docker run -d --name mysql -p 8080:80 ${{ steps.login-ecr.outputs.registry }}/clo835-assignment1-sql-image:v0.1        
+    #     EOF
